import React, { useState } from 'react';
import { LayoutDashboard, FileText, BarChart3, LineChart, PieChart, Download, FileDown, Presentation, Target, Activity, Settings2, Video, MonitorPlay, Code2 as Github, Database, Server, Box, Eye, RefreshCw, Shield, Play, Lock, CheckSquare } from 'lucide-react';
import PresentationViewer from './PresentationViewer';
import Bloc4VisualizationDemo from './demos/Bloc4VisualizationDemo';
import Bloc4GithubRepo from './Bloc4GithubRepo';
import {
    LineChart as RechartsLineChart,
    Line,
    XAxis,
    YAxis,
    CartesianGrid,
    Tooltip,
    Legend,
    ResponsiveContainer,
    BarChart,
    Bar,
    PieChart as RechartsPieChart,
    Pie,
    Cell
} from 'recharts';

export default function Bloc4Visualization() {
    const [activeTab, setActiveTab] = useState<'presentation' | 'repository' | 'demo' | 'techspecs'>('presentation');
    const [dashboardView, setDashboardView] = useState<'summary' | 'detail' | 'forecast'>('summary');
    const [yearFilter, setYearFilter] = useState('2026');

    const renderIcon = (Icon: any, label: string) => (
        <div className="flex flex-col items-center justify-center animate-in fade-in zoom-in duration-500">
            <Icon size={72} strokeWidth={1.5} className="mb-4 text-emerald-400" />
            <span className="font-bold tracking-widest uppercase text-sm text-emerald-300">{label}</span>
        </div>
    );

    const presentationSlides = [
        { num: 1, title: "Title & Objective", content: "End-to-End AI Solution for Aurora Tech", script: "Good morning. For Bloc 4, I will present our end-to-end AI Solution, designed to predict margin risks and trigger financial supply-chain actions.", visualComponent: renderIcon(Target, "AI Solutions") },
        { num: 2, title: "Problem Definition", content: "Fx fluctuations + Shipping delays = Margin Crash", script: "Our core problem is volatility. When the Euro drops and shipping delays rise simultaneously, our 8% margin is wiped out.", visualComponent: renderIcon(Activity, "Margin Risk") },
        { num: 3, title: "Data Inputs", content: "Warehouse Data (Postgres) -> EUR/USD, Shipping Delay, Freight Cost", script: "We extract structured training data directly from our Bloc 2 Data Warehouse: historical FX rates, calculated component delays, and freight costs.", visualComponent: renderIcon(Database, "Data Sourcing") },
        { num: 4, title: "Algorithm Selection", content: "Why Random Forest Classifier?", script: "We selected a Random Forest Classifier. It handles non-linear relationships well, such as the interaction between currency parity and sudden sea-to-air freight conversions.", visualComponent: renderIcon(LineChart, "Random Forest") },
        { num: 5, title: "Model Training", content: "Scikit-Learn, Hyperparameter tuning", script: "We trained the model on 5 years of historical financial data using Scikit-Learn, optimizing for recall to ensure we never miss a critical margin risk event.", visualComponent: renderIcon(Settings2, "Model Training") },
        { num: 6, title: "Serving Infrastructure", content: "FastAPI Implementation", script: "To industrialize the model, we wrapped the saved joblib artifact in a high-performance Python FastAPI service, exposing a /predict-margin-risk JSON endpoint.", visualComponent: renderIcon(Server, "FastAPI Service") },
        { num: 7, title: "Deployment Architecture", content: "Docker Containerization", script: "We containerized the entire API using Docker, ensuring that the machine learning environment and dependencies remain identical from dev to production.", visualComponent: renderIcon(Box, "Dockerization") },
        { num: 8, title: "CI/CD Pipeline", content: "GitHub Actions", script: "For Continuous Integration, we use GitHub Actions. Every commit triggers automated PyTest gates to verify model integrity before deploying to the Cloud Run server.", visualComponent: renderIcon(Github, "CI/CD Actions") },
        { num: 9, title: "Production Monitoring", content: "Data Drift & Concept Drift", script: "We monitor the model in production using statistical tools. If EUR/USD volatility shifts outside historical bounds, the system detects data drift.", visualComponent: renderIcon(Eye, "Drift Monitoring") },
        { num: 10, title: "Automated Retraining", content: "Triggered by Drift Alerts", script: "Upon detecting drift, an automated pipeline triggers a retraining script, appending the latest data, building a new joblib artifact, and rolling it out.", visualComponent: renderIcon(RefreshCw, "Auto-Retraining") },
        { num: 11, title: "Business Output", content: "Predictions fed to the BI Dashboard", script: "The predictions generated by this API are directly fed into our PowerBI-style visual dashboard, alerting executives to expected margin compressions.", visualComponent: renderIcon(LayoutDashboard, "BI Integration") },
        { num: 12, title: "Web3 Hedging Trigger", content: "Trigger USDC token purchases", script: "When probability of extreme loss exceeds 85%, the API issues an alert to our Web3 smart contract infrastructure, triggering instant USDC currency locking to bypass banking delays.", visualComponent: renderIcon(Shield, "Web3 Action") },
        { num: 13, title: "Live Demonstration", content: "Loom Video: Triggering the API", script: "In our upcoming video demonstration, you will see a simulated POST request hitting the API, returning a critical risk warning, and rendering on the dashboard.", visualComponent: renderIcon(Play, "Solution Demo") },
        { num: 14, title: "Ethical & Security Considerations", content: "API Key Auth, Role-based Access", script: "We secure our prediction endpoint using strict API token authentication, preventing unauthorized competitors from querying our margin risk logic.", visualComponent: renderIcon(Lock, "API Security") },
        { num: 15, title: "Conclusion", content: "Closing statement & Q&A", script: "In summary, our MLOps architecture bridges predictive AI with automated business action. Thank you, I am ready for the Q&A.", visualComponent: renderIcon(CheckSquare, "Ready for Q&A") }
    ];

    // Mock Data
    const fxData = [
        { month: 'Jan', eurUsd: 1.09, eurTwd: 35.1, shippingCost: 20 },
        { month: 'Feb', eurUsd: 1.08, eurTwd: 34.8, shippingCost: 25 },
        { month: 'Mar', eurUsd: 1.05, eurTwd: 34.2, shippingCost: 35 },
        { month: 'Apr', eurUsd: 1.03, eurTwd: 33.9, shippingCost: 45 },
        { month: 'May', eurUsd: 1.06, eurTwd: 34.5, shippingCost: 30 },
        { month: 'Jun', eurUsd: 1.07, eurTwd: 34.7, shippingCost: 25 },
    ];

    const vendorData = [
        { name: 'NVIDIA (GPU)', cost: 400 },
        { name: 'TSMC (CPU)', cost: 300 },
        { name: 'AUO (Display)', cost: 300 },
    ];
    const COLORS = ['#10b981', '#3b82f6', '#f43f5e'];

    const forecastData = [
        { month: 'Jul', actual: null, forecast: 1.08, lowerBound: 1.06, upperBound: 1.10 },
        { month: 'Aug', actual: null, forecast: 1.09, lowerBound: 1.06, upperBound: 1.12 },
        { month: 'Sep', actual: null, forecast: 1.07, lowerBound: 1.04, upperBound: 1.10 },
    ];

    const handleExportWord = () => {
        const contentBlock = document.getElementById('tech-specs-content');
        if (!contentBlock) return;
        
        const preHtml = `<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
        <head><meta charset='utf-8'><title>Technical Specs</title></head><body>`;
        const postHtml = "</body></html>";
        const html = preHtml + contentBlock.innerHTML + postHtml;

        const blob = new Blob(['\ufeff', html], { type: 'application/msword' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = 'Technical_Specifications_Bloc4.doc';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    return (
        <div className="p-4 md:p-8 max-w-6xl mx-auto animate-in fade-in duration-500 h-full flex flex-col">
            <header className="mb-8 border-b border-slate-200 pb-6 shrink-0">
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                    <div>
                        <div className="flex items-center gap-3 text-emerald-600 mb-2">
                            <Target size={28} />
                            <h2 className="text-3xl font-extrabold text-slate-900 tracking-tight">Bloc 4: AI Solutions & Dashboards</h2>
                        </div>
                        <p className="text-lg text-slate-600 mt-2">Deliverables: AI Presentation (15 Slides), Model & CI/CD Repo, Demo Video</p>
                    </div>
                </div>

                <div className="flex flex-wrap gap-2 mt-8">
                    <button 
                        onClick={() => setActiveTab('presentation')}
                        className={`flex items-center gap-2 px-5 py-3 text-sm font-bold rounded-t-lg border-b-2 transition-all ${activeTab === 'presentation' ? 'border-emerald-600 text-emerald-700 bg-emerald-50/50' : 'border-transparent text-slate-500 hover:bg-slate-50'}`}
                    >
                        <Presentation size={18} />
                        Deliverable 1: AI Defense Plan
                    </button>
                    <button 
                        onClick={() => setActiveTab('repository')}
                        className={`flex items-center gap-2 px-5 py-3 text-sm font-bold rounded-t-lg border-b-2 transition-all ${activeTab === 'repository' ? 'border-slate-800 text-slate-900 bg-slate-100/50' : 'border-transparent text-slate-500 hover:bg-slate-50'}`}
                    >
                        <Github size={18} />
                        Deliverable 2 & 3: Model & CI/CD Code
                    </button>
                    <button 
                        onClick={() => setActiveTab('demo')}
                        className={`flex items-center gap-2 px-5 py-3 text-sm font-bold rounded-t-lg border-b-2 transition-all ${activeTab === 'demo' ? 'border-rose-500 text-rose-700 bg-rose-50/50' : 'border-transparent text-slate-500 hover:bg-slate-50'}`}
                    >
                        <MonitorPlay size={18} />
                        Deliverable 4: AI Dashboard Demo
                    </button>
                    <button 
                        onClick={() => setActiveTab('techspecs')}
                        className={`flex items-center gap-2 px-5 py-3 text-sm font-bold rounded-t-lg border-b-2 transition-all ${activeTab === 'techspecs' ? 'border-amber-500 text-amber-700 bg-amber-50/50' : 'border-transparent text-slate-500 hover:bg-slate-50'}`}
                    >
                        <FileText size={18} />
                        Bonus: BI Technical Specs
                    </button>
                </div>
            </header>

            <div className="flex-1 overflow-y-auto">
                {activeTab === 'presentation' && (
                    <div className="animate-in slide-in-from-bottom-4 duration-500 fade-in">
                        <div className="bg-emerald-950 rounded-2xl p-8 shadow-xl text-white mb-8 border border-emerald-800">
                            <div className="flex items-center gap-3 mb-6">
                                <Target size={32} className="text-emerald-400" />
                                <div>
                                    <h3 className="text-2xl font-bold text-white">AI Solution Defense Presentation</h3>
                                    <p className="text-emerald-200 mt-1">Format: 5-minute presentation + 10-minute Q&A.</p>
                                </div>
                            </div>
                            <PresentationViewer title="Atomic-Link: Predictive AI Infrastructure" slides={presentationSlides} accentColor="emerald" />
                        </div>
                    </div>
                )}

                {activeTab === 'demo' && (
                    <div className="animate-in slide-in-from-bottom-4 duration-500 fade-in pb-8">
                        <div className="mb-6 p-4 bg-rose-50 text-rose-900 rounded-lg border border-rose-200">
                            <h3 className="font-bold flex items-center gap-2"><Video size={20} /> AI Solutions Demo Screencast</h3>
                            <p className="text-sm mt-1">Demo of the end-to-end flow: from AI prediction to Dashboard Visualization. This fulfills the 5-minute video deliverable.</p>
                        </div>
                        <div className="bg-white border text-left border-gray-200 rounded-xl overflow-hidden shadow-sm font-sans flex flex-col min-h-[700px]">
                            {/* Dashboard Header */}
                            <div className="bg-slate-900 text-white px-6 py-4 flex flex-col md:flex-row md:items-center justify-between gap-4">
                                <div>
                                    <h3 className="text-xl font-bold flex items-center gap-2"><BarChart3 size={24} className="text-emerald-400" /> Aurora Tech Operations Center</h3>
                                    <p className="text-slate-400 text-sm mt-1">Live from PostgreSQL Data Warehouse • Last Refreshed: Just now</p>
                                </div>
                                <div className="flex items-center gap-3">
                                    <select 
                                        className="bg-slate-800 border border-slate-700 text-sm rounded-md px-3 py-1.5 focus:outline-none focus:ring-2 focus:ring-emerald-500"
                                        value={yearFilter}
                                        onChange={(e) => setYearFilter(e.target.value)}
                                    >
                                        <option value="2026">FY 2026</option>
                                        <option value="2025">FY 2025</option>
                                    </select>
                                    <button className="flex items-center gap-2 px-3 py-1.5 bg-emerald-600 hover:bg-emerald-500 text-white rounded-md text-sm font-medium transition-colors">
                                        <Download size={16} /> Export
                                    </button>
                                </div>
                            </div>
                            
                            {/* Dashboard Nav */}
                            <div className="border-b border-gray-200 bg-gray-50 px-4 flex gap-4">
                                <button onClick={() => setDashboardView('summary')} className={`py-3 px-2 text-sm font-semibold border-b-2 ${dashboardView === 'summary' ? 'border-emerald-500 text-emerald-700' : 'border-transparent text-gray-500 hover:text-gray-700'}`}>Executive Summary</button>
                                <button onClick={() => setDashboardView('detail')} className={`py-3 px-2 text-sm font-semibold border-b-2 ${dashboardView === 'detail' ? 'border-emerald-500 text-emerald-700' : 'border-transparent text-gray-500 hover:text-gray-700'}`}>Logistics & Cost Detail</button>
                                <button onClick={() => setDashboardView('forecast')} className={`py-3 px-2 text-sm font-semibold border-b-2 ${dashboardView === 'forecast' ? 'border-emerald-500 text-emerald-700' : 'border-transparent text-gray-500 hover:text-gray-700'}`}>FX Forecasting</button>
                            </div>

                            {/* Dashboard Content Area */}
                            <div className="p-6 bg-slate-50 flex-1">
                                {dashboardView === 'summary' && (
                                    <div className="space-y-6 animate-in fade-in">
                                        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                                            <div className="bg-white p-5 rounded-xl border border-gray-200 shadow-sm">
                                                <div className="text-gray-500 text-sm font-medium mb-1">Avg EUR/USD ({yearFilter})</div>
                                                <div className="text-3xl font-bold text-gray-900">1.063</div>
                                                <div className="text-red-500 text-sm mt-2 flex items-center gap-1 font-medium"><LineChart size={14}/> -2.4% vs Last Year</div>
                                            </div>
                                            <div className="bg-white p-5 rounded-xl border border-gray-200 shadow-sm">
                                                <div className="text-gray-500 text-sm font-medium mb-1">Total Freight Spends</div>
                                                <div className="text-3xl font-bold text-gray-900">€ 1.2M</div>
                                                <div className="text-red-500 text-sm mt-2 flex items-center gap-1 font-medium"><LineChart size={14}/> +15% vs Last Year</div>
                                            </div>
                                            <div className="bg-white p-5 rounded-xl border border-gray-200 shadow-sm">
                                                <div className="text-gray-500 text-sm font-medium mb-1">Impacted Margin Events</div>
                                                <div className="text-3xl font-bold text-gray-900">24</div>
                                                <div className="text-yellow-600 text-sm mt-2 flex items-center gap-1 font-medium"><Target size={14}/> Action Required</div>
                                            </div>
                                        </div>
                                        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                                            <div className="bg-white p-5 rounded-xl border border-gray-200 shadow-sm h-80 flex flex-col">
                                                <h4 className="font-semibold text-gray-800 mb-4">Currency vs Shipping Cost Trend</h4>
                                                <div className="flex-1 min-h-0">
                                                    <ResponsiveContainer width="100%" height="100%">
                                                        <RechartsLineChart data={fxData}>
                                                            <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#E5E7EB"/>
                                                            <XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fill: '#6B7280', fontSize: 12}} />
                                                            <YAxis yAxisId="left" axisLine={false} tickLine={false} tick={{fill: '#6B7280', fontSize: 12}} domain={['dataMin - 0.02', 'dataMax + 0.02']}/>
                                                            <YAxis yAxisId="right" orientation="right" axisLine={false} tickLine={false} tick={{fill: '#6B7280', fontSize: 12}}/>
                                                            <Tooltip contentStyle={{borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)'}}/>
                                                            <Legend wrapperStyle={{fontSize: '12px'}}/>
                                                            <Line yAxisId="left" type="monotone" dataKey="eurUsd" name="EUR / USD" stroke="#3b82f6" strokeWidth={3} dot={{r: 4, fill: '#3b82f6', strokeWidth: 0}} activeDot={{r: 6}} />
                                                            <Line yAxisId="right" type="monotone" dataKey="shippingCost" name="Avg Shipping €" stroke="#f43f5e" strokeWidth={3} dot={{r: 4, fill: '#f43f5e', strokeWidth: 0}} activeDot={{r: 6}} />
                                                        </RechartsLineChart>
                                                    </ResponsiveContainer>
                                                </div>
                                            </div>
                                            <div className="bg-white p-5 rounded-xl border border-gray-200 shadow-sm h-80 flex flex-col">
                                                <h4 className="font-semibold text-gray-800 mb-4">Cost Distribution by Vendor</h4>
                                                <div className="flex-1 min-h-0">
                                                    <ResponsiveContainer width="100%" height="100%">
                                                        <RechartsPieChart>
                                                            <Pie data={vendorData} cx="50%" cy="50%" innerRadius={60} outerRadius={80} paddingAngle={5} dataKey="cost">
                                                                {vendorData.map((entry, index) => <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />)}
                                                            </Pie>
                                                            <Tooltip contentStyle={{borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)'}}/>
                                                            <Legend wrapperStyle={{fontSize: '12px'}}/>
                                                        </RechartsPieChart>
                                                    </ResponsiveContainer>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                )}

                                {dashboardView === 'detail' && (
                                    <div className="bg-white p-5 rounded-xl border border-gray-200 shadow-sm h-[500px] flex flex-col animate-in fade-in">
                                         <h4 className="font-semibold text-gray-800 mb-4">Logistics Detailed Analysis</h4>
                                         <div className="flex-1 min-h-0">
                                            <ResponsiveContainer width="100%" height="100%">
                                                <BarChart data={fxData}>
                                                    <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#E5E7EB"/>
                                                    <XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fill: '#6B7280', fontSize: 12}} />
                                                    <YAxis axisLine={false} tickLine={false} tick={{fill: '#6B7280', fontSize: 12}}/>
                                                    <Tooltip cursor={{fill: '#F3F4F6'}} contentStyle={{borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)'}}/>
                                                    <Legend wrapperStyle={{fontSize: '12px'}}/>
                                                    <Bar dataKey="shippingCost" name="Freight Cost (EUR)" fill="#10b981" radius={[4, 4, 0, 0]} />
                                                </BarChart>
                                            </ResponsiveContainer>
                                         </div>
                                    </div>
                                )}

                                {dashboardView === 'forecast' && (
                                    <div className="bg-white p-5 rounded-xl border border-gray-200 shadow-sm h-[500px] flex flex-col animate-in fade-in">
                                        <h4 className="font-semibold text-gray-800 mb-4 items-center flex gap-2"><Activity size={18} className="text-emerald-500" /> EUR/USD Predictive Forecast (Next 3 Months)</h4>
                                         <div className="flex-1 min-h-0">
                                            <ResponsiveContainer width="100%" height="100%">
                                                <RechartsLineChart data={forecastData}>
                                                    <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#E5E7EB"/>
                                                    <XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fill: '#6B7280', fontSize: 12}} />
                                                    <YAxis domain={[1.00, 1.15]} axisLine={false} tickLine={false} tick={{fill: '#6B7280', fontSize: 12}}/>
                                                    <Tooltip contentStyle={{borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)'}}/>
                                                    <Legend wrapperStyle={{fontSize: '12px'}}/>
                                                    <Line type="monotone" dataKey="forecast" name="Forecast EUR/USD" stroke="#6366f1" strokeWidth={3} strokeDasharray="5 5" dot={{r: 4, fill: '#6366f1', strokeWidth: 0}} activeDot={{r: 6}} />
                                                    <Line type="step" dataKey="upperBound" name="Upper Confidence Bounds" stroke="#cbd5e1" strokeWidth={2} dot={false} activeDot={false} />
                                                    <Line type="step" dataKey="lowerBound" name="Lower Confidence Bounds" stroke="#cbd5e1" strokeWidth={2} dot={false} activeDot={false} />
                                                </RechartsLineChart>
                                            </ResponsiveContainer>
                                         </div>
                                    </div>
                                )}
                            </div>
                        </div>
                        <div className="max-w-4xl mx-auto mt-8">
                            <Bloc4VisualizationDemo />
                        </div>
                    </div>
                )}

                {activeTab === 'techspecs' && (
                    <div className="animate-in slide-in-from-bottom-4 duration-500 fade-in pb-8">
                        <div className="bg-white text-slate-800 p-8 md:p-12 border border-gray-200 rounded-xl shadow-sm my-4">
                            <div className="mb-8 flex justify-between items-center border-b border-gray-200 pb-6">
                                <div>
                                    <h1 className="text-3xl font-extrabold text-slate-900 tracking-tight">Technical Specifications Document</h1>
                                    <p className="text-slate-500 mt-2 font-medium">Dashboard Architecture & UI/UX Guidelines</p>
                                </div>
                                <button 
                                    onClick={handleExportWord}
                                    className="flex items-center gap-2 bg-slate-800 hover:bg-slate-700 text-white px-5 py-2.5 rounded-lg font-bold shadow-md transition-all active:scale-95"
                                >
                                    <FileDown size={18} /> Export as PDF/MD
                                </button>
                            </div>
                            
                            <div id="tech-specs-content" className="space-y-8 leading-relaxed font-serif text-lg">
                                <h2>1. Data Connection Architecture</h2>
                                <p>The dashboard is powered by a direct secure connection to the <strong>PostgreSQL Data Warehouse</strong> (deployed in Bloc 2), refreshed via Apache Airflow pipelines (Bloc 3). Connection method utilized is `DirectQuery` to ensure real-time fidelity of Freight constraints and FX fluctuations.</p>
                                
                                <h2>2. Calculated Fields & Measures</h2>
                                <p>Essential DAX/Calculated fields implemented:</p>
                                <ul>
                                    <li><code>MarginImpactRisk = IF([freight_cost_eur] {">"} 40 OR [eur_usd] {"<"} 1.05, 1, 0)</code></li>
                                    <li><code>TotalFreightSpend = SUM(fact_margin_risk[freight_cost_eur])</code></li>
                                    <li><code>YoY_FX_Variance = ([Avg_EUR_USD_Current] - [Avg_EUR_USD_Prior]) / [Avg_EUR_USD_Prior]</code></li>
                                </ul>

                                <h2>3. UI/UX Rationale</h2>
                                <p>Design choices adhere to cognitive load reduction principles:</p>
                                <ul>
                                    <li><strong>Color Palette:</strong> Neutral slate backgrounds with high-contrast semantic highlights (Emerald for positive, Rose for warnings/costs). Emerald/Blue mappings are used for color-blind accessibility.</li>
                                    <li><strong>Typography:</strong> Sans-serif strictly used for data-ink ratio maximization.</li>
                                    <li><strong>Interactivity:</strong> Multi-tab navigation avoids vertical scrolling fatigue. Cross-filtering enabled across all visuals (e.g. clicking a Vendor instantly filters the FX chart).</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                )}

                {activeTab === 'repository' && (
                    <div className="animate-in slide-in-from-bottom-4 duration-500 fade-in pb-8">
                         <div className="mb-6 p-4 bg-slate-50 text-slate-700 rounded-lg border border-slate-200">
                            <h3 className="font-bold flex items-center gap-2 text-slate-800"><Github size={20} className="text-slate-600" /> AI Solutions & MLOps Source Code</h3>
                            <p className="text-sm mt-1">Simulated public GitHub repository containing the Random Forest prediction model, FastAPI service, and GitHub Actions CI/CD workflows.</p>
                        </div>
                        <Bloc4GithubRepo />
                    </div>
                )}
            </div>
        </div>
    );
}
